/* Generated By:JavaCC: Do not edit this line. ELParserConstants.java */
package com.intrbiz.express.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ELParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NON_EXPRESSION_TEXT = 1;
  /** RegularExpression Id. */
  int START_EXPRESSION = 2;
  /** RegularExpression Id. */
  int START_SCRIPT = 3;
  /** RegularExpression Id. */
  int DIGITS = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int ADD = 11;
  /** RegularExpression Id. */
  int SUB = 12;
  /** RegularExpression Id. */
  int MUL = 13;
  /** RegularExpression Id. */
  int DIV = 14;
  /** RegularExpression Id. */
  int DIV1 = 15;
  /** RegularExpression Id. */
  int POW = 16;
  /** RegularExpression Id. */
  int MOD = 17;
  /** RegularExpression Id. */
  int MOD1 = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int EQ1 = 20;
  /** RegularExpression Id. */
  int EQ2 = 21;
  /** RegularExpression Id. */
  int NE = 22;
  /** RegularExpression Id. */
  int NE1 = 23;
  /** RegularExpression Id. */
  int NE2 = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int GT1 = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int LT1 = 28;
  /** RegularExpression Id. */
  int GTEQ = 29;
  /** RegularExpression Id. */
  int GTEQ1 = 30;
  /** RegularExpression Id. */
  int LTEQ = 31;
  /** RegularExpression Id. */
  int LTEQ1 = 32;
  /** RegularExpression Id. */
  int BITWISE_OR = 33;
  /** RegularExpression Id. */
  int BITWISE_XOR = 34;
  /** RegularExpression Id. */
  int BITWISE_AND = 35;
  /** RegularExpression Id. */
  int BITWISE_NOT = 36;
  /** RegularExpression Id. */
  int BITSHIFT_LEFT = 37;
  /** RegularExpression Id. */
  int BITSHIFT_RIGHT = 38;
  /** RegularExpression Id. */
  int BITSHIFT_URIGHT = 39;
  /** RegularExpression Id. */
  int OR = 40;
  /** RegularExpression Id. */
  int OR1 = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int AND1 = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int NOT1 = 45;
  /** RegularExpression Id. */
  int STCOMP = 46;
  /** RegularExpression Id. */
  int EDCOMP = 47;
  /** RegularExpression Id. */
  int ARGSEP = 48;
  /** RegularExpression Id. */
  int STARR = 49;
  /** RegularExpression Id. */
  int EDARR = 50;
  /** RegularExpression Id. */
  int ASSIGNMENT = 51;
  /** RegularExpression Id. */
  int ADDASSIGNMENT = 52;
  /** RegularExpression Id. */
  int SUBASSIGNMENT = 53;
  /** RegularExpression Id. */
  int MULASSIGNMENT = 54;
  /** RegularExpression Id. */
  int DIVASSIGNMENT = 55;
  /** RegularExpression Id. */
  int POWASSIGNMENT = 56;
  /** RegularExpression Id. */
  int MODASSIGNMENT = 57;
  /** RegularExpression Id. */
  int INCASSIGNMENT = 58;
  /** RegularExpression Id. */
  int DECASSIGNMENT = 59;
  /** RegularExpression Id. */
  int ARROW = 60;
  /** RegularExpression Id. */
  int STATEMENT = 61;
  /** RegularExpression Id. */
  int NEW = 62;
  /** RegularExpression Id. */
  int RETURN = 63;
  /** RegularExpression Id. */
  int IF = 64;
  /** RegularExpression Id. */
  int ELSE = 65;
  /** RegularExpression Id. */
  int IN = 66;
  /** RegularExpression Id. */
  int FOR = 67;
  /** RegularExpression Id. */
  int WHILE = 68;
  /** RegularExpression Id. */
  int BREAK = 69;
  /** RegularExpression Id. */
  int CONTINUE = 70;
  /** RegularExpression Id. */
  int EXPORT = 71;
  /** RegularExpression Id. */
  int INCLUDE = 72;
  /** RegularExpression Id. */
  int FUNCTION = 73;
  /** RegularExpression Id. */
  int LACTION = 74;
  /** RegularExpression Id. */
  int COLON = 75;
  /** RegularExpression Id. */
  int NLINT = 76;
  /** RegularExpression Id. */
  int NLLONG = 77;
  /** RegularExpression Id. */
  int NLFLOAT = 78;
  /** RegularExpression Id. */
  int NLDOUBLE = 79;
  /** RegularExpression Id. */
  int LBOOLEAN = 80;
  /** RegularExpression Id. */
  int LNULL = 81;
  /** RegularExpression Id. */
  int LENTITY = 82;
  /** RegularExpression Id. */
  int HEXCHAR = 83;
  /** RegularExpression Id. */
  int ESCAPECHAR = 84;
  /** RegularExpression Id. */
  int UESCAPECHAR = 85;
  /** RegularExpression Id. */
  int LSTRING = 86;
  /** RegularExpression Id. */
  int STARTMAP = 87;
  /** RegularExpression Id. */
  int ENDMAP = 88;
  /** RegularExpression Id. */
  int END_EXPRESSION = 89;
  /** RegularExpression Id. */
  int QUOTE = 90;
  /** RegularExpression Id. */
  int STARTBLOCK = 91;
  /** RegularExpression Id. */
  int ENDBLOCK = 92;
  /** RegularExpression Id. */
  int END_SCRIPT = 93;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 96;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 97;
  /** RegularExpression Id. */
  int ENDQUOTE = 100;
  /** RegularExpression Id. */
  int CHAR = 101;
  /** RegularExpression Id. */
  int CNTRLESC = 102;
  /** RegularExpression Id. */
  int HEX = 104;
  /** RegularExpression Id. */
  int HEXESC = 105;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_EXPRESSION = 1;
  /** Lexical state. */
  int IN_SCRIPT = 2;
  /** Lexical state. */
  int IN_MAP = 3;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 4;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 5;
  /** Lexical state. */
  int STRINGSTATE = 6;
  /** Lexical state. */
  int ESCSTATE = 7;
  /** Lexical state. */
  int HEXSTATE = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NON_EXPRESSION_TEXT>",
    "\"#{\"",
    "\"<#\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<DIGITS>",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"^\"",
    "\"%\"",
    "\"mod\"",
    "\"==\"",
    "\"eq\"",
    "\"===\"",
    "\"!=\"",
    "\"ne\"",
    "\"!==\"",
    "\">\"",
    "\"gt\"",
    "\"<\"",
    "\"lt\"",
    "\">=\"",
    "\"gteq\"",
    "\"<=\"",
    "\"lteq\"",
    "\"|\"",
    "<BITWISE_XOR>",
    "\"&\"",
    "\"~\"",
    "\"<<\"",
    "\">>\"",
    "<BITSHIFT_URIGHT>",
    "<OR>",
    "\"or\"",
    "<AND>",
    "\"and\"",
    "\"!\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"^=\"",
    "\"%=\"",
    "\"++\"",
    "\"--\"",
    "\"->\"",
    "\";\"",
    "\"new\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"in\"",
    "\"for\"",
    "\"while\"",
    "\"break\"",
    "\"continue\"",
    "\"export\"",
    "\"include\"",
    "\"function\"",
    "\"@\"",
    "\":\"",
    "<NLINT>",
    "<NLLONG>",
    "<NLFLOAT>",
    "<NLDOUBLE>",
    "<LBOOLEAN>",
    "<LNULL>",
    "<LENTITY>",
    "<HEXCHAR>",
    "<ESCAPECHAR>",
    "<UESCAPECHAR>",
    "<LSTRING>",
    "\"{\"",
    "\"}\"",
    "\"}\"",
    "\"\\\"\"",
    "\"{\"",
    "\"}\"",
    "\"#>\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 98>",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRLESC>",
    "\"u\"",
    "<HEX>",
    "<HEXESC>",
  };

}
