/* Generated By:JavaCC: Do not edit this line. ELParserConstants.java */
package com.intrbiz.express.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ELParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGITS = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int SUB = 9;
  /** RegularExpression Id. */
  int MUL = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int DIV1 = 12;
  /** RegularExpression Id. */
  int POW = 13;
  /** RegularExpression Id. */
  int MOD = 14;
  /** RegularExpression Id. */
  int MOD1 = 15;
  /** RegularExpression Id. */
  int EQ = 16;
  /** RegularExpression Id. */
  int EQ1 = 17;
  /** RegularExpression Id. */
  int NE = 18;
  /** RegularExpression Id. */
  int NE1 = 19;
  /** RegularExpression Id. */
  int GT = 20;
  /** RegularExpression Id. */
  int GT1 = 21;
  /** RegularExpression Id. */
  int LT = 22;
  /** RegularExpression Id. */
  int LT1 = 23;
  /** RegularExpression Id. */
  int GTEQ = 24;
  /** RegularExpression Id. */
  int GTEQ1 = 25;
  /** RegularExpression Id. */
  int LTEQ = 26;
  /** RegularExpression Id. */
  int LTEQ1 = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int OR1 = 29;
  /** RegularExpression Id. */
  int AND = 30;
  /** RegularExpression Id. */
  int AND1 = 31;
  /** RegularExpression Id. */
  int NOT = 32;
  /** RegularExpression Id. */
  int NOT1 = 33;
  /** RegularExpression Id. */
  int STCOMP = 34;
  /** RegularExpression Id. */
  int EDCOMP = 35;
  /** RegularExpression Id. */
  int ARGSEP = 36;
  /** RegularExpression Id. */
  int STARR = 37;
  /** RegularExpression Id. */
  int EDARR = 38;
  /** RegularExpression Id. */
  int NEW = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int ELSE = 42;
  /** RegularExpression Id. */
  int IN = 43;
  /** RegularExpression Id. */
  int FOR = 44;
  /** RegularExpression Id. */
  int WHILE = 45;
  /** RegularExpression Id. */
  int BREAK = 46;
  /** RegularExpression Id. */
  int EXPORT = 47;
  /** RegularExpression Id. */
  int STARTBLOCK = 48;
  /** RegularExpression Id. */
  int ENDBLOCK = 49;
  /** RegularExpression Id. */
  int ASSIGNMENT = 50;
  /** RegularExpression Id. */
  int ADDASSIGNMENT = 51;
  /** RegularExpression Id. */
  int SUBASSIGNMENT = 52;
  /** RegularExpression Id. */
  int MULASSIGNMENT = 53;
  /** RegularExpression Id. */
  int DIVASSIGNMENT = 54;
  /** RegularExpression Id. */
  int POWASSIGNMENT = 55;
  /** RegularExpression Id. */
  int MODASSIGNMENT = 56;
  /** RegularExpression Id. */
  int INCASSIGNMENT = 57;
  /** RegularExpression Id. */
  int DECASSIGNMENT = 58;
  /** RegularExpression Id. */
  int STATEMENT = 59;
  /** RegularExpression Id. */
  int LACTION = 60;
  /** RegularExpression Id. */
  int NLINT = 61;
  /** RegularExpression Id. */
  int NLLONG = 62;
  /** RegularExpression Id. */
  int NLFLOAT = 63;
  /** RegularExpression Id. */
  int NLDOUBLE = 64;
  /** RegularExpression Id. */
  int LBOOLEAN = 65;
  /** RegularExpression Id. */
  int LNULL = 66;
  /** RegularExpression Id. */
  int LENTITY = 67;
  /** RegularExpression Id. */
  int HEXCHAR = 68;
  /** RegularExpression Id. */
  int ESCAPECHAR = 69;
  /** RegularExpression Id. */
  int UESCAPECHAR = 70;
  /** RegularExpression Id. */
  int LSTRING = 71;
  /** RegularExpression Id. */
  int QUOTE = 72;
  /** RegularExpression Id. */
  int ENDQUOTE = 74;
  /** RegularExpression Id. */
  int CHAR = 75;
  /** RegularExpression Id. */
  int CNTRLESC = 76;
  /** RegularExpression Id. */
  int HEX = 78;
  /** RegularExpression Id. */
  int HEXESC = 79;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRINGSTATE = 1;
  /** Lexical state. */
  int ESCSTATE = 2;
  /** Lexical state. */
  int HEXSTATE = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<DIGITS>",
    "\".\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"div\"",
    "\"^\"",
    "\"%\"",
    "\"mod\"",
    "\"==\"",
    "\"eq\"",
    "\"!=\"",
    "\"ne\"",
    "\">\"",
    "\"gt\"",
    "\"<\"",
    "\"lt\"",
    "\">=\"",
    "\"gteq\"",
    "\"<=\"",
    "\"lteq\"",
    "\"||\"",
    "\"or\"",
    "\"&&\"",
    "\"and\"",
    "\"!\"",
    "\"not\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"new\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"in\"",
    "\"for\"",
    "\"while\"",
    "\"break\"",
    "\"export\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"^=\"",
    "\"%=\"",
    "\"++\"",
    "\"--\"",
    "\";\"",
    "\"@\"",
    "<NLINT>",
    "<NLLONG>",
    "<NLFLOAT>",
    "<NLDOUBLE>",
    "<LBOOLEAN>",
    "<LNULL>",
    "<LENTITY>",
    "<HEXCHAR>",
    "<ESCAPECHAR>",
    "<UESCAPECHAR>",
    "<LSTRING>",
    "\"\\\"\"",
    "\"\\\\\"",
    "<ENDQUOTE>",
    "<CHAR>",
    "<CNTRLESC>",
    "\"u\"",
    "<HEX>",
    "<HEXESC>",
  };

}
